spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        enabled: true
        all-namespaces: false
        primary-port-name: "default-http"
        discovery-server-url: "http://netflix-eureka-server"
        include-not-ready-addresses: true
        locator:
          enabled: false
          lowerCaseServiceId: true
  config:
    import: optional:configserver:http://config-server

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

