apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ms.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
          - name: "{{ .Values.ms.imagePullSecrets }}"
      containers:
        - image: "{{ .Values.ms.image.repository }}"
          tag: {{ .Values.ms.image.tag }}
          imagePullPolicy: {{ .Values.ms.imagePullPolicy }}
          name: {{ .Release.Name }}
          {{- if .Values.ms.container.args }}
          args:
            {{- range $arg := .Values.ms.container.args }}
            - "{{ $arg }}"
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet: # make an HTTP request
              port: {{ .Values.ms.service.targetPort }} # port to use
              path: {{ .Values.ms.livenessProbe }}/actuator/health # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 30 # how long to wait before checking
            periodSeconds: 60 # how long to wait between checks
            timeoutSeconds: 10 # how long to wait for a response
            failureThreshold: 5
          readinessProbe:
            httpGet: # make an HTTP request
              port: {{ .Values.ms.service.targetPort }} # port to use
              path: {{ .Values.ms.readinessProbe }}/actuator/health # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 30 # how long to wait before checking
            periodSeconds: 60 # how long to wait between checks
            timeoutSeconds: 10 # how long to wait for a response
            failureThreshold: 5
      restartPolicy: Always
