apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.ms.service.type }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: {{ .Values.ms.service.targetPort }}
  selector:
    app: {{ .Release.Name }}