ms:
  image:
    repository: abhinavymca/config-server
    tag:
  imagePullPolicy: Always
  spec:
    replicas: 1
  service:
    targetPort: 8080
    type: ClusterIP
  livenessProbe:
  readinessProbe:
  container:
    args:
      - "java"
      - "-jar"
      - "app.jar"
      - "--server.port=8080"
