spring:
  application:
    name: netflix-eureka-server
  config:
    import: optional:configserver:http://config-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false