ms:
  image:
    repository: abhinavymca/user-ms
    tag:
  imagePullPolicy: Always
  spec:
    replicas: 1
  service:
    targetPort: 8080
    type: ClusterIP
  livenessProbe: /user-ms
  readinessProbe: /user-ms
